<a href="https://colab.research.google.com/github/sheena-k/hrmodel/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("aug_train.csv")

In [ ]:
data["major_discipline"].replace(["Business Degree", "No Major"],
                             ["Business_Degree","No_Major"],inplace=True)

In [ ]:
data["enrolled_university"].replace(["Full time course", "Part time course"],
                             ['Full_time_course','Part_time_course'],inplace=True)

In [ ]:
data["education_level"].replace(["High School", "Primary School"],
                             ['High_School','Primary_School'],inplace=True)

In [ ]:
data["company_type"].replace(["Pvt Ltd","Funded Startup","Public Sector","Early Stage Startup"],
                             ["Pvt_Ltd","Funded_Startup","Public_Sector","Early_Stage_Startup"],inplace=True)

In [ ]:
data["company_size"].replace(["<10","10/49", "50-99", "100-500", "500-999", "1000-4999", "5000-9999", "10000+"],
                             ["Startup","Small","Small","Medium","Medium","Large","Large","Large"],inplace=True)


In [ ]:
data["relevent_experience"].replace(["Has relevent experience", "No relevent experience"],
                             ['Yes','No'],inplace=True)

In [ ]:
data["last_new_job"].replace([">4","never"],
                        ['5',"0"],inplace=True)

In [ ]:
data["experience"].replace([">20","<1"],["21","0"],inplace=True)

In [ ]:
data["education_level"].unique()

array(['Graduate', 'Masters', 'High_School', nan, 'Phd', 'Primary_School'],
      dtype=object)

In [ ]:
data["company_size"].fillna(value="NW",inplace=True) #not working yet
data["company_type"].fillna(value="NW",inplace=True)
data["gender"].fillna(value="DNM",inplace=True)

In [ ]:
data["enrolled_university"].fillna(data["enrolled_university"].mode()[0],inplace=True)

In [ ]:
data["education_level"].fillna(data["education_level"].mode()[0],inplace=True)

In [ ]:

data["major_discipline"].fillna(data["major_discipline"].mode()[0],inplace =True)

In [ ]:
data["last_new_job"].fillna(data["last_new_job"].mode()[0],inplace=True)

In [ ]:
data["experience"].fillna(data["experience"].mode()[0],inplace=True)

In [ ]:
data = data.astype({'last_new_job':'int'})

In [ ]:
data["experience"] = data["experience"].astype(int)

In [ ]:
data["education_level"].unique()

array(['Graduate', 'Masters', 'High_School', 'Phd', 'Primary_School'],
      dtype=object)

In [ ]:
data["company_size"].unique()

array(['NW', 'Small', 'Startup', 'Large', 'Medium'], dtype=object)

In [ ]:
data["gender"].unique()

array(['Male', 'DNM', 'Female', 'Other'], dtype=object)

In [ ]:
data.isnull().sum()

enrollee_id               0
city                      0
city_development_index    0
gender                    0
relevent_experience       0
enrolled_university       0
education_level           0
major_discipline          0
experience                0
company_size              0
company_type              0
last_new_job              0
training_hours            0
target                    0
dtype: int64

In [ ]:

train=data.drop(['enrollee_id',"city"],axis=1) # dropping enrollee id and city
train

city_development_index gender relevent_experience enrolled_university  \
0                       0.920   Male                 Yes       no_enrollment   
1                       0.776   Male                  No       no_enrollment   
2                       0.624    DNM                  No    Full_time_course   
3                       0.789    DNM                  No       no_enrollment   
4                       0.767   Male                 Yes       no_enrollment   
...                       ...    ...                 ...                 ...   
19153                   0.878   Male                  No       no_enrollment   
19154                   0.920   Male                 Yes       no_enrollment   
19155                   0.920   Male                 Yes       no_enrollment   
19156                   0.802   Male                 Yes       no_enrollment   
19157                   0.855    DNM                  No       no_enrollment   

      education_level major_discipline  experience company_size  \
0            Graduate             STEM          21           NW   
1            Graduate             STEM          15        Small   
2            Graduate             STEM           5           NW   
3            Graduate  Business_Degree           0           NW   
4             Masters             STEM          21        Small   
...               ...              ...         ...          ...   
19153        Graduate       Humanities          14           NW   
19154        Graduate             STEM          14           NW   
19155        Graduate             STEM          21        Small   
19156     High_School             STEM           0       Medium   
19157  Primary_School             STEM           2           NW   

         company_type  last_new_job  training_hours  target  
0                  NW             1              36     1.0  
1             Pvt_Ltd             5              47     0.0  
2                  NW             0              83     0.0  
3             Pvt_Ltd             0              52     1.0  
4      Funded_Startup             4               8     0.0  
...               ...           ...             ...     ...  
19153              NW             1              42     1.0  
19154              NW             4              52     1.0  
19155         Pvt_Ltd             4              44     0.0  
19156         Pvt_Ltd             2              97     0.0  
19157              NW             1             127     0.0  

[19158 rows x 12 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:

le= LabelEncoder()

In [ ]:
train["relevent_experience"] = le.fit_transform(train["relevent_experience"])

In [ ]:
train["relevent_experience"].unique()

array([1, 0])

In [ ]:
train["education_level"] = le.fit_transform(train["education_level"])

In [ ]:
train["education_level"].unique()

array([0, 2, 1, 3, 4])

In [ ]:
train["last_new_job"].unique()

array([1, 5, 0, 4, 3, 2])

In [ ]:
train["experience"] = train["experience"].astype(int)

In [ ]:
train["last_new_job"] = train["last_new_job"].astype(int)

In [ ]:

train["company_size"] = le.fit_transform(train["company_size"])

In [ ]:
train["company_size"].unique()

array([2, 3, 4, 0, 1])

In [ ]:

train["gender"] = le.fit_transform(train["gender"])

In [ ]:
train["gender"].unique()

array([2, 0, 1, 3])

In [ ]:
train = pd.get_dummies(train)

In [ ]:
X = train.drop("target",axis=1)
Y = pd.DataFrame(train["target"])


In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:

smote = SMOTE()
X,Y = smote.fit_resample(X,Y)

In [ ]:
X.tail()

city_development_index  gender  relevent_experience  education_level  \
28757                0.624000       2                    1                2   
28758                0.917986       2                    1                0   
28759                0.746827       0                    0                0   
28760                0.920000       2                    0                0   
28761                0.742341       0                    1                0   

       experience  company_size  last_new_job  training_hours  \
28757           3             2             1             130   
28758          21             2             5               7   
28759           4             2             1               9   
28760          16             2             0              17   
28761           8             3             1              44   

       enrolled_university_Full_time_course  \
28757                                     0   
28758                                     0   
28759                                     0   
28760                                     0   
28761                                     0   

       enrolled_university_Part_time_course  ...  major_discipline_No_Major  \
28757                                     0  ...                          0   
28758                                     0  ...                          0   
28759                                     0  ...                          0   
28760                                     0  ...                          0   
28761                                     0  ...                          0   

       major_discipline_Other  major_discipline_STEM  \
28757                       0                      1   
28758                       0                      1   
28759                       0                      1   
28760                       0                      0   
28761                       0                      1   

       company_type_Early_Stage_Startup  company_type_Funded_Startup  \
28757                                 0                            0   
28758                                 0                            0   
28759                                 0                            0   
28760                                 0                            0   
28761                                 0                            0   

       company_type_NGO  company_type_NW  company_type_Other  \
28757                 0                0                   0   
28758                 0                1                   0   
28759                 0                1                   0   
28760                 0                1                   0   
28761                 0                0                   0   

       company_type_Public_Sector  company_type_Pvt_Ltd  
28757                           0                     0  
28758                           0                     0  
28759                           0                     0  
28760                           0                     0  
28761                           0                     1  

[5 rows x 24 columns]

In [ ]:
Y= np.squeeze(Y)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size = 0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_cls =RandomForestClassifier()

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
model_rf = rf_cls.fit(x_train,y_train)

In [ ]:
y_pred_rf = model_rf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred_rf)

0.8362593429515036

In [ ]:
import pickle

In [ ]:
filename="savemodel.pickle"

In [ ]:
with open(filename,"wb") as file:
  pickle.dump(model_rf,file)